### ISSUE TITLE
Deleted model

### ISSUE THREAD

**Issue by qoffee** [armando2603/master-thesis#1]
Hello! I tried to use your model. For this I wanted to download the pre-trained weights from the [link](https://drive.google.com/file/d/1-TZmS_LVmoO9a_mPgdr8aRJgPf6B0Kjp/view?usp=sharing) to google but , but the link is not valid. Can you update the link with weights reuploaded? Thanks.

**Comment by armando2603** [comment]
Thank you for the report. The link is working again
